In [1]:
import mysql.connector
import pandas as pd

In [2]:
dataset = pd.read_csv('dataset.csv')
dataset.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
import csv

In [7]:
try:
    connection = mysql.connector.connect(host='localhost', database='new_database', user='root', password='brihad1692')

    mySql_Create_Table_Query = """CREATE TABLE diseases( 
                                                        Disease varchar(250),
                                                        Symptom_1 varchar(250),
                                                        Symptom_2 varchar(250),
                                                        Symptom_3 varchar(250),
                                                        Symptom_4 varchar(250),
                                                        Symptom_5 varchar(250),
                                                        Symptom_6 varchar(250),
                                                        Symptom_7 varchar(250),
                                                        Symptom_8 varchar(250),
                                                        Symptom_9 varchar(250),
                                                        Symptom_10 varchar(250),
                                                        Symptom_11 varchar(250),
                                                        Symptom_12 varchar(250),
                                                        Symptom_13 varchar(250),
                                                        Symptom_14 varchar(250),
                                                        Symptom_15 varchar(250),
                                                        Symptom_16 varchar(250),
                                                        Symptom_17 varchar(250),
                                                        Vacant varchar(10)
                                                        ) """

    cursor = connection.cursor()
    result = cursor.execute(mySql_Create_Table_Query)
    print("diseases Table created successfully ")



except mysql.connector.Error as error:
    print("Failed to create table in MySQL: {}".format(error))

finally:
    if connection.is_connected():
        cursor.close()
        connection.close()
        print("MySQL connection is closed")

diseases Table created successfully
MySQL connection is closed

In [8]:
dataset.head()

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6,Symptom_7,Symptom_8,Symptom_9,Symptom_10,Symptom_11,Symptom_12,Symptom_13,Symptom_14,Symptom_15,Symptom_16,Symptom_17
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
entries = ""
counter = 1

with open('dataset.csv') as file_obj:
    heading = next(file_obj)
    reader_obj = csv.reader(file_obj)
    for row in reader_obj:
        #print(row)
        for value in row:
            #print(value)
            entries = entries + "'" + value + "'" + ", "
            #print(entries)
        try:
            connection = mysql.connector.connect(host='localhost', database='new_database', user='root', password='brihad1692')

            sql_insert_stmt = "insert into diseases values(" + entries + " '');"

            print(sql_insert_stmt)
            
            entries = ""
            
            cursor = connection.cursor()
            result = cursor.execute(sql_insert_stmt)
            print(f"inserted {counter} entries")
            counter = counter + 1



        except mysql.connector.Error as error:
            print("Failed to add value in MySQL: {}".format(error))

        finally:
            if connection.is_connected():
                cursor.close()
                connection.close()
                print("MySQL connection is closed")

insert into diseases values('Fungal infection', 'itching', ' skin_rash', ' nodal_skin_eruptions', ' dischromic _patches', '', '', '', '', '', '', '', '', '', '', '', '', '',  '');
inserted 1 entries
MySQL connection is closed
insert into diseases values('Fungal infection', ' skin_rash', ' nodal_skin_eruptions', ' dischromic _patches', '', '', '', '', '', '', '', '', '', '', '', '', '', '',  '');
inserted 2 entries
MySQL connection is closed
insert into diseases values('Fungal infection', 'itching', ' nodal_skin_eruptions', ' dischromic _patches', '', '', '', '', '', '', '', '', '', '', '', '', '', '',  '');
inserted 3 entries
MySQL connection is closed
insert into diseases values('Fungal infection', 'itching', ' skin_rash', ' dischromic _patches', '', '', '', '', '', '', '', '', '', '', '', '', '', '',  '');
inserted 4 entries
MySQL connection is closed
insert into diseases values('Fungal infection', 'itching', ' skin_rash', ' nodal_skin_eruptions', '', '', '', '', '', '', '', '', '', '', '', '', '', '',  '');
inserted 5 entries
MySQL connection is closed
insert into diseases values('Fungal infection', ' skin_rash', ' nodal_skin_eruptions', ' dischromic _patches', '', '', '', '', '', '', '', '', '', '', '', '', '', '',  '');
inserted 6 entries
MySQL connection is closed
insert into diseases values('Fungal infection', 'itching', ' nodal_skin_eruptions', ' dischromic _patches', '', '', '', '', '', '', '', '', '', '', '', '', '', '',  '');
inserted 7 entries
MySQL connection is closed
insert into diseases values('Fungal infection', 'itching', ' skin_rash', ' dischromic _patches', '', '', '', '', '', '', '', '', '', '', '', '', '', '',  '');
inserted 8 entries
MySQL connection is closed
insert into diseases values('Fungal infection', 'itching', ' skin_rash', ' nodal_skin_eruptions', '', '', '', '', '', '', '', '', '', '', '', '', '', '',  '');
inserted 9 entries
MySQL connection is closed
insert into diseases values('Fungal infection', 'itching', ' skin_rash', ' nodal_skin_eruptions', ' dischromic _patches', '', '', '', '', '', '', '', '', '', '', '', '', '',  '');
inserted 10 entries
MySQL connection is closed
insert into diseases values('Diabetes ', ' fatigue', ' weight_loss', ' restlessness', ' lethargy', ' irregular_sugar_level', ' blurred_and_distorted_vision', ' obesity', ' excessive_hunger', ' increased_appetite', ' polyuria', '', '', '', '', '', '', '',  '');
inserted 11 entries
MySQL connection is closed
insert into diseases values('Diabetes ', ' fatigue', ' weight_loss', ' restlessness', ' lethargy', ' irregular_sugar_level', ' blurred_and_distorted_vision', ' obesity', ' excessive_hunger', ' increased_appetite', ' polyuria', '', '', '', '', '', '', '',  '');
inserted 12 entries
MySQL connection is closed
insert into diseases values('Diabetes ', ' weight_loss', ' restlessness', ' lethargy', ' irregular_sugar_level', ' blurred_and_distorted_vision', ' obesity', ' excessive_hunger', ' increased_appetite', ' polyuria', '', '', '', '', '', '', '', '',  '');
inserted 13 entries
MySQL connection is closed
insert into diseases values('Diabetes ', ' fatigue', ' restlessness', ' lethargy', ' irregular_sugar_level', ' blurred_and_distorted_vision', ' obesity', ' excessive_hunger', ' increased_appetite', ' polyuria', '', '', '', '', '', '', '', '',  '');
inserted 14 entries
MySQL connection is closed
insert into diseases values('Diabetes ', ' fatigue', ' weight_loss', ' lethargy', ' irregular_sugar_level', ' blurred_and_distorted_vision', ' obesity', ' excessive_hunger', ' increased_appetite', ' polyuria', '', '', '', '', '', '', '', '',  '');
inserted 15 entries
MySQL connection is closed
insert into diseases values('Diabetes ', ' fatigue', ' weight_loss', ' restlessness', ' irregular_sugar_level', ' blurred_and_distorted_vision', ' obesity', ' excessive_hunger', ' increased_appetite', ' polyuria', '', '', '', '', '', '', '', '',  '');
inserted 16 entries
MySQL connection is closed
insert into diseases values('Diabetes ', ' fatigue', ' weight_loss', ' restlessness', ' lethargy', ' blurred_and_distorted_vision', ' obesity', ' excessive_hunger', ' increased_appetite', ' polyuria', '', '', '', '', '', '', '', '',  '');
inserted 17 entries
MySQL connection is closed
insert into diseases values('Diabetes ', ' fatigue', ' weight_loss', ' restlessness', ' lethargy', ' irregular_sugar_level', ' obesity', ' excessive_hunger', ' increased_appetite', ' polyuria', '', '', '', '', '', '', '', '',  '');
inserted 18 entries
MySQL connection is closed
insert into diseases values('Diabetes ', ' fatigue', ' weight_loss', ' restlessness', ' lethargy', ' irregular_sugar_level', ' blurred_and_distorted_vision', ' excessive_hunger', ' increased_appetite', ' polyuria', '', '', '', '', '', '', '', '',  '');
inserted 19 entries
MySQL connection is closed
insert into diseases values('Diabetes ', ' fatigue', ' weight_loss', ' restlessness', ' lethargy', ' irregular_sugar_level', ' blurred_and_distorted_vision', ' obesity', ' increased_appetite', ' polyuria', '', '', '', '', '', '', '', '',  '');
inserted 20 entries
MySQL connection is closed
insert into diseases values('Jaundice', 'itching', ' vomiting', ' fatigue', ' weight_loss', ' high_fever', ' yellowish_skin', ' dark_urine', ' abdominal_pain', '', '', '', '', '', '', '', '', '',  '');
inserted 21 entries
MySQL connection is closed
insert into diseases values('Jaundice', 'itching', ' vomiting', ' fatigue', ' weight_loss', ' high_fever', ' yellowish_skin', ' dark_urine', ' abdominal_pain', '', '', '', '', '', '', '', '', '',  '');
inserted 22 entries
MySQL connection is closed
insert into diseases values('Jaundice', ' vomiting', ' fatigue', ' weight_loss', ' high_fever', ' yellowish_skin', ' dark_urine', ' abdominal_pain', '', '', '', '', '', '', '', '', '', '',  '');
inserted 23 entries
MySQL connection is closed
insert into diseases values('Jaundice', 'itching', ' fatigue', ' weight_loss', ' high_fever', ' yellowish_skin', ' dark_urine', ' abdominal_pain', '', '', '', '', '', '', '', '', '', '',  '');
inserted 24 entries
MySQL connection is closed
insert into diseases values('Jaundice', 'itching', ' vomiting', ' weight_loss', ' high_fever', ' yellowish_skin', ' dark_urine', ' abdominal_pain', '', '', '', '', '', '', '', '', '', '',  '');
inserted 25 entries
MySQL connection is closed
insert into diseases values('Jaundice', 'itching', ' vomiting', ' fatigue', ' high_fever', ' yellowish_skin', ' dark_urine', ' abdominal_pain', '', '', '', '', '', '', '', '', '', '',  '');
inserted 26 entries
MySQL connection is closed
insert into diseases values('Jaundice', 'itching', ' vomiting', ' fatigue', ' weight_loss', ' yellowish_skin', ' dark_urine', ' abdominal_pain', '', '', '', '', '', '', '', '', '', '',  '');
inserted 27 entries
MySQL connection is closed
insert into diseases values('Jaundice', 'itching', ' vomiting', ' fatigue', ' weight_loss', ' high_fever', ' dark_urine', ' abdominal_pain', '', '', '', '', '', '', '', '', '', '',  '');
inserted 28 entries
MySQL connection is closed
insert into diseases values('Jaundice', 'itching', ' vomiting', ' fatigue', ' weight_loss', ' high_fever', ' yellowish_skin', ' abdominal_pain', '', '', '', '', '', '', '', '', '', '',  '');
inserted 29 entries
MySQL connection is closed
insert into diseases values('Jaundice', 'itching', ' vomiting', ' fatigue', ' weight_loss', ' high_fever', ' yellowish_skin', ' dark_urine', '', '', '', '', '', '', '', '', '', '',  '');
inserted 30 entries
MySQL connection is closed
insert into diseases values('Malaria', ' chills', ' vomiting', ' high_fever', ' sweating', ' headache', ' nausea', ' muscle_pain', '', '', '', '', '', '', '', '', '', '',  '');
inserted 31 entries
MySQL connection is closed
insert into diseases values('Malaria', ' chills', ' vomiting', ' high_fever', ' sweating', ' headache', ' nausea', ' diarrhoea', ' muscle_pain', '', '', '', '', '', '', '', '', '',  '');
inserted 32 entries
MySQL connection is closed
insert into diseases values('Malaria', ' chills', ' vomiting', ' high_fever', ' sweating', ' headache', ' nausea', ' diarrhoea', ' muscle_pain', '', '', '', '', '', '', '', '', '',  '');
inserted 33 entries
MySQL connection is closed
insert into diseases values('Malaria', ' vomiting', ' high_fever', ' sweating', ' headache', ' nausea', ' diarrhoea', ' muscle_pain', '', '', '', '', '', '', '', '', '', '',  '');
inserted 34 entries
MySQL connection is closed
insert into diseases values('Malaria', ' chills', ' high_fever', ' sweating', ' headache', ' nausea', ' diarrhoea', ' muscle_pain', '', '', '', '', '', '', '', '', '', '',  '');
inserted 35 entries
MySQL connection is closed
insert into diseases values('Malaria', ' chills', ' vomiting', ' sweating', ' headache', ' nausea', ' diarrhoea', ' muscle_pain', '', '', '', '', '', '', '', '', '', '',  '');
inserted 36 entries
MySQL connection is closed
insert into diseases values('Malaria', ' chills', ' vomiting', ' high_fever', ' headache', ' nausea', ' diarrhoea', ' muscle_pain', '', '', '', '', '', '', '', '', '', '',  '');
inserted 37 entries
MySQL connection is closed
insert into diseases values('Malaria', ' chills', ' vomiting', ' high_fever', ' sweating', ' nausea', ' diarrhoea', ' muscle_pain', '', '', '', '', '', '', '', '', '', '',  '');
inserted 38 entries
MySQL connection is closed
insert into diseases values('Malaria', ' chills', ' vomiting', ' high_fever', ' sweating', ' headache', ' diarrhoea', ' muscle_pain', '', '', '', '', '', '', '', '', '', '',  '');
inserted 39 entries
MySQL connection is closed
insert into diseases values('Malaria', ' chills', ' vomiting', ' high_fever', ' sweating', ' headache', ' nausea', ' muscle_pain', '', '', '', '', '', '', '', '', '', '',  '');
inserted 40 entries
MySQL connection is closed
insert into diseases values('Dengue', ' skin_rash', ' chills', ' joint_pain', ' vomiting', ' fatigue', ' high_fever', ' headache', ' nausea', ' loss_of_appetite', ' pain_behind_the_eyes', ' back_pain', ' muscle_pain', ' red_spots_over_body', '', '', '', '',  '');
inserted 41 entries
MySQL connection is closed
insert into diseases values('Dengue', ' skin_rash', ' chills', ' joint_pain', ' vomiting', ' fatigue', ' high_fever', ' headache', ' nausea', ' loss_of_appetite', ' pain_behind_the_eyes', ' back_pain', ' malaise', ' red_spots_over_body', '', '', '', '',  '');
inserted 42 entries
MySQL connection is closed
insert into diseases values('Dengue', ' skin_rash', ' chills', ' joint_pain', ' vomiting', ' fatigue', ' high_fever', ' headache', ' nausea', ' loss_of_appetite', ' pain_behind_the_eyes', ' back_pain', ' malaise', ' muscle_pain', '', '', '', '',  '');
inserted 43 entries
MySQL connection is closed
insert into diseases values('Dengue', ' skin_rash', ' chills', ' joint_pain', ' vomiting', ' fatigue', ' high_fever', ' headache', ' nausea', ' loss_of_appetite', ' pain_behind_the_eyes', ' back_pain', ' malaise', ' muscle_pain', ' red_spots_over_body', '', '', '',  '');
inserted 44 entries
MySQL connection is closed
insert into diseases values('Dengue', ' chills', ' joint_pain', ' vomiting', ' fatigue', ' high_fever', ' headache', ' nausea', ' loss_of_appetite', ' pain_behind_the_eyes', ' back_pain', ' malaise', ' muscle_pain', ' red_spots_over_body', '', '', '', '',  '');
inserted 45 entries
MySQL connection is closed
insert into diseases values('Dengue', ' skin_rash', ' joint_pain', ' vomiting', ' fatigue', ' high_fever', ' headache', ' nausea', ' loss_of_appetite', ' pain_behind_the_eyes', ' back_pain', ' malaise', ' muscle_pain', ' red_spots_over_body', '', '', '', '',  '');
inserted 46 entries
MySQL connection is closed
insert into diseases values('Dengue', ' skin_rash', ' chills', ' vomiting', ' fatigue', ' high_fever', ' headache', ' nausea', ' loss_of_appetite', ' pain_behind_the_eyes', ' back_pain', ' malaise', ' muscle_pain', ' red_spots_over_body', '', '', '', '',  '');
inserted 47 entries
MySQL connection is closed
insert into diseases values('Dengue', ' skin_rash', ' chills', ' joint_pain', ' fatigue', ' high_fever', ' headache', ' nausea', ' loss_of_appetite', ' pain_behind_the_eyes', ' back_pain', ' malaise', ' muscle_pain', ' red_spots_over_body', '', '', '', '',  '');
inserted 48 entries
MySQL connection is closed
insert into diseases values('Dengue', ' skin_rash', ' chills', ' joint_pain', ' vomiting', ' high_fever', ' headache', ' nausea', ' loss_of_appetite', ' pain_behind_the_eyes', ' back_pain', ' malaise', ' muscle_pain', ' red_spots_over_body', '', '', '', '',  '');
inserted 49 entries
MySQL connection is closed
insert into diseases values('Dengue', ' skin_rash', ' chills', ' joint_pain', ' vomiting', ' fatigue', ' headache', ' nausea', ' loss_of_appetite', ' pain_behind_the_eyes', ' back_pain', ' malaise', ' muscle_pain', ' red_spots_over_body', '', '', '', '',  '');
inserted 50 entries
MySQL connection is closed
insert into diseases values('Typhoid', ' chills', ' vomiting', ' fatigue', ' high_fever', ' nausea', ' constipation', ' abdominal_pain', ' diarrhoea', ' toxic_look_(typhos)', ' belly_pain', '', '', '', '', '', '', '',  '');
inserted 51 entries
MySQL connection is closed
insert into diseases values('Typhoid', ' chills', ' vomiting', ' fatigue', ' high_fever', ' headache', ' constipation', ' abdominal_pain', ' diarrhoea', ' toxic_look_(typhos)', ' belly_pain', '', '', '', '', '', '', '',  '');
inserted 52 entries
MySQL connection is closed
insert into diseases values('Typhoid', ' chills', ' vomiting', ' fatigue', ' high_fever', ' headache', ' nausea', ' abdominal_pain', ' diarrhoea', ' toxic_look_(typhos)', ' belly_pain', '', '', '', '', '', '', '',  '');
inserted 53 entries
MySQL connection is closed
insert into diseases values('Typhoid', ' chills', ' vomiting', ' fatigue', ' high_fever', ' headache', ' nausea', ' constipation', ' diarrhoea', ' toxic_look_(typhos)', ' belly_pain', '', '', '', '', '', '', '',  '');
inserted 54 entries
MySQL connection is closed
insert into diseases values('Typhoid', ' chills', ' vomiting', ' fatigue', ' high_fever', ' headache', ' nausea', ' constipation', ' abdominal_pain', ' toxic_look_(typhos)', ' belly_pain', '', '', '', '', '', '', '',  '');
inserted 55 entries
MySQL connection is closed
insert into diseases values('Typhoid', ' chills', ' vomiting', ' fatigue', ' high_fever', ' headache', ' nausea', ' constipation', ' abdominal_pain', ' diarrhoea', ' belly_pain', '', '', '', '', '', '', '',  '');
inserted 56 entries
MySQL connection is closed
insert into diseases values('Typhoid', ' chills', ' vomiting', ' fatigue', ' high_fever', ' headache', ' nausea', ' constipation', ' abdominal_pain', ' diarrhoea', ' toxic_look_(typhos)', '', '', '', '', '', '', '',  '');
inserted 57 entries
MySQL connection is closed
insert into diseases values('Typhoid', ' chills', ' vomiting', ' fatigue', ' high_fever', ' headache', ' nausea', ' constipation', ' abdominal_pain', ' diarrhoea', ' toxic_look_(typhos)', ' belly_pain', '', '', '', '', '', '',  '');
inserted 58 entries
MySQL connection is closed
insert into diseases values('Typhoid', ' chills', ' vomiting', ' fatigue', ' high_fever', ' headache', ' nausea', ' constipation', ' abdominal_pain', ' diarrhoea', ' toxic_look_(typhos)', ' belly_pain', '', '', '', '', '', '',  '');
inserted 59 entries
MySQL connection is closed
insert into diseases values('Typhoid', ' chills', ' fatigue', ' high_fever', ' headache', ' nausea', ' constipation', ' abdominal_pain', ' diarrhoea', ' toxic_look_(typhos)', ' belly_pain', '', '', '', '', '', '', '',  '');
inserted 60 entries
MySQL connection is closed
insert into diseases values('Common Cold', ' continuous_sneezing', ' chills', ' fatigue', ' cough', ' high_fever', ' headache', ' swelled_lymph_nodes', ' malaise', ' phlegm', ' throat_irritation', ' redness_of_eyes', ' sinus_pressure', ' runny_nose', ' congestion', ' chest_pain', ' loss_of_smell', '',  '');
inserted 61 entries
MySQL connection is closed
insert into diseases values('Common Cold', ' continuous_sneezing', ' chills', ' fatigue', ' cough', ' high_fever', ' headache', ' swelled_lymph_nodes', ' malaise', ' phlegm', ' throat_irritation', ' redness_of_eyes', ' sinus_pressure', ' runny_nose', ' congestion', ' chest_pain', ' loss_of_smell', '',  '');
inserted 62 entries
MySQL connection is closed
insert into diseases values('Common Cold', ' chills', ' fatigue', ' cough', ' high_fever', ' headache', ' swelled_lymph_nodes', ' malaise', ' phlegm', ' throat_irritation', ' redness_of_eyes', ' sinus_pressure', ' runny_nose', ' congestion', ' chest_pain', ' loss_of_smell', ' muscle_pain', '',  '');
inserted 63 entries
MySQL connection is closed
insert into diseases values('Common Cold', ' continuous_sneezing', ' fatigue', ' cough', ' high_fever', ' headache', ' swelled_lymph_nodes', ' malaise', ' phlegm', ' throat_irritation', ' redness_of_eyes', ' sinus_pressure', ' runny_nose', ' congestion', ' chest_pain', ' loss_of_smell', ' muscle_pain', '',  '');
inserted 64 entries
MySQL connection is closed
insert into diseases values('Common Cold', ' continuous_sneezing', ' chills', ' cough', ' high_fever', ' headache', ' swelled_lymph_nodes', ' malaise', ' phlegm', ' throat_irritation', ' redness_of_eyes', ' sinus_pressure', ' runny_nose', ' congestion', ' chest_pain', ' loss_of_smell', ' muscle_pain', '',  '');
inserted 65 entries
MySQL connection is closed
insert into diseases values('Common Cold', ' continuous_sneezing', ' chills', ' fatigue', ' high_fever', ' headache', ' swelled_lymph_nodes', ' malaise', ' phlegm', ' throat_irritation', ' redness_of_eyes', ' sinus_pressure', ' runny_nose', ' congestion', ' chest_pain', ' loss_of_smell', ' muscle_pain', '',  '');
inserted 66 entries
MySQL connection is closed
insert into diseases values('Common Cold', ' continuous_sneezing', ' chills', ' fatigue', ' cough', ' headache', ' swelled_lymph_nodes', ' malaise', ' phlegm', ' throat_irritation', ' redness_of_eyes', ' sinus_pressure', ' runny_nose', ' congestion', ' chest_pain', ' loss_of_smell', ' muscle_pain', '',  '');
inserted 67 entries
MySQL connection is closed
insert into diseases values('Common Cold', ' continuous_sneezing', ' chills', ' fatigue', ' cough', ' high_fever', ' swelled_lymph_nodes', ' malaise', ' phlegm', ' throat_irritation', ' redness_of_eyes', ' sinus_pressure', ' runny_nose', ' congestion', ' chest_pain', ' loss_of_smell', ' muscle_pain', '',  '');
inserted 68 entries
MySQL connection is closed
insert into diseases values('Common Cold', ' continuous_sneezing', ' chills', ' fatigue', ' cough', ' high_fever', ' headache', ' malaise', ' phlegm', ' throat_irritation', ' redness_of_eyes', ' sinus_pressure', ' runny_nose', ' congestion', ' chest_pain', ' loss_of_smell', ' muscle_pain', '',  '');
inserted 69 entries
MySQL connection is closed
insert into diseases values('Common Cold', ' continuous_sneezing', ' chills', ' fatigue', ' cough', ' high_fever', ' headache', ' swelled_lymph_nodes', ' phlegm', ' throat_irritation', ' redness_of_eyes', ' sinus_pressure', ' runny_nose', ' congestion', ' chest_pain', ' loss_of_smell', ' muscle_pain', '',  '');
inserted 70 entries
MySQL connection is closed
insert into diseases values('Pneumonia', ' chills', ' fatigue', ' cough', ' high_fever', ' breathlessness', ' sweating', ' malaise', ' chest_pain', ' fast_heart_rate', ' rusty_sputum', '', '', '', '', '', '', '',  '');
inserted 71 entries
MySQL connection is closed
insert into diseases values('Pneumonia', ' chills', ' fatigue', ' cough', ' high_fever', ' breathlessness', ' sweating', ' malaise', ' phlegm', ' chest_pain', ' fast_heart_rate', ' rusty_sputum', '', '', '', '', '', '',  '');
inserted 72 entries
MySQL connection is closed
insert into diseases values('Pneumonia', ' chills', ' fatigue', ' cough', ' high_fever', ' breathlessness', ' sweating', ' malaise', ' phlegm', ' chest_pain', ' fast_heart_rate', ' rusty_sputum', '', '', '', '', '', '',  '');
inserted 73 entries
MySQL connection is closed